[package]
name = "Qr_code"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.3"
image = "0.25.6"
qrcode = "0.14.1"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.1", features = ["full"] }
